<template>
  <div>
    <Html>
      <Head>
        <Title>Medusa + Nuxt App</Title>
        <Meta name="description" content="Generated by npx nuxi init" />
        <Link rel="icon" href="/favicon.ico" />
      </Head>
    </Html>
    <Layout>
      <NuxtPage />
    </Layout>
  </div>
</template>

<script setup lang="ts">
import { useStore } from "~/stores/useStore";

const { initialize } = useStore();
await useAsyncData("init-medusa", () => initialize());
</script>
