<template>
  <div>
    <Html>
      <Head>
        <Title>Medusa + Nuxt App</Title>
        <Meta name="description" content="Generated by npx nuxi init" />
        <Link rel="icon" href="/favicon.ico" />
      </Head>
    </Html>
    <NuxtPage />
  </div>
</template>
